package main

import (
	"log"
	"os"

	"SAMA_DATA_API/internal/config"
	"SAMA_DATA_API/internal/handlers"
	"SAMA_DATA_API/internal/repository"
	"SAMA_DATA_API/internal/routes"
	"SAMA_DATA_API/internal/service"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/swagger"

	// Docs generated by Swag CLI
	_ "SAMA_DATA_API/docs"
)

// @title SAMA_DATA API
// @version 1.0
// @description High Performance TimeSeries Data Interface for SAMA IoT.
// @host localhost:3000
// @BasePath /
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name X-API-Key
func main() {
	// Initialize Config & Database
	config.LoadEnv()
	config.ConnectDB()
	defer config.CloseDB()

	// Dependency Injection Setup
	// Repositories
	stationRepo := repository.NewStationRepository()
	variableRepo := repository.NewVariableRepository()
	measurementRepo := repository.NewMeasurementRepository()

	// Services
	stationService := service.NewStationService(stationRepo)
	variableService := service.NewVariableService(variableRepo)
	measurementService := service.NewMeasurementService(measurementRepo)

	// Handlers
	stationHandler := handlers.NewStationHandler(stationService)
	variableHandler := handlers.NewVariableHandler(variableService)
	measurementHandler := handlers.NewMeasurementHandler(measurementService)

	// Initialize Fiber App
	app := fiber.New(fiber.Config{
		AppName: "SAMA_DATA API - High Performance TSDB Interface",
	})

	// Middlewares
	app.Use(logger.New())
	app.Use(recover.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "Origin, Content-Type, Accept, X-API-Key",
	}))

	// Setup Routes
	routes.SetupRoutes(app, stationHandler, variableHandler, measurementHandler)

	// Swagger Route
	app.Get("/swagger/*", swagger.HandlerDefault)

	// Start Server
	port := os.Getenv("PORT") // Use PORT from environment (required for Cloud Run)
	if port == "" {
		port = os.Getenv("API_PORT") // Fallback to API_PORT if set
		if port == "" {
			port = "3000" // Default port
		}
	}

	log.Printf("Server is running on port %s", port)
	log.Fatal(app.Listen(":" + port))
}
